apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taiji-postgres-data
  labels:
    app.kubernetes.io/part-of: taiji
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rancher-local-path
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taiji-redis-data
  labels:
    app.kubernetes.io/part-of: taiji
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rancher-local-path
  resources:
    requests:
      storage: 5Gi
