apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lihao
resources:
  - 01-configmap.yaml
  - 03-storage.yaml
  - 04-postgres.yaml
  - 05-redis.yaml
  - 07-keycloak.yaml
  - 09-backend.yaml
  - 10-worker.yaml
  - 12-frontend.yaml
  - 13-init-jobs.yaml
